# Generated by Django 3.2 on 2023-03-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название категории', max_length=256, verbose_name='название категории')),
                ('slug', models.SlugField(help_text='введите слаг категории', unique=True, verbose_name='слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ведите название жанра', max_length=256, verbose_name='название жанра')),
                ('slug', models.SlugField(help_text='введите слаг жанра', unique=True, verbose_name='слаг жанра')),
            ],
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название рпоизведения', max_length=256, verbose_name='название произведения')),
                ('year', models.PositiveIntegerField(help_text='введите год издания', verbose_name='год производства')),
                ('description', models.TextField(blank=True, help_text='введите описание произведения', null=True, verbose_name='описание произведения')),
                ('category', models.ForeignKey(blank=True, help_text='введите тип произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='тип произведения')),
                ('genre', models.ManyToManyField(help_text='введите жанр произведения', related_name='title', through='reviews.GenreTitle', to='reviews.Genre', verbose_name='жанр произведения')),
            ],
        ),
        migrations.AddField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.title'),
        ),
    ]
