# Generated by Django 3.2 on 2023-04-02 15:22

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_unique_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='введите название категории', max_length=256, unique=True, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='ведите название жанра', max_length=256, unique=True, verbose_name='название жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(help_text='введите год издания', validators=[reviews.validators.validate_year], verbose_name='год производства'),
        ),
    ]
